version: '3'

services: 
    webapp:
        build: .
        volumes:
            - .:/var/www/html/:ro
        depends_on:
            - db
        ports:
            - "8000:80"
    db:
        build: sql/
        environment: 
            MYSQL_ROOT_PASSWORD: guestbook