version: '3'

services: 
    webapp:
        image: php:7-apache
        volumes:
            - .:/var/www/html/
        depends_on:
            - db
        ports:
            - "8000:80"
    db:
        build: .